# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "f2bread"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Atmatzidis Panagiotis"]
  s.date = "2013-07-01"
  s.description = "A simple gem that reads 'fail2ban.log' and displays statistics"
  s.email = "atma@convalesco.org"
  s.executables = ["f2bread"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/f2bread",
    "f2bread.gemspec",
    "lib/GeoIP.dat",
    "lib/f2bread.rb",
    "test/helper.rb",
    "test/test_f2bread.rb"
  ]
  s.homepage = "http://github.com/atmosx/f2bread"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Fail2ban statistics"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<geoip>, ["~> 1.2.1"])
      s.add_development_dependency(%q<time_diff>, ["~> 0.3.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<geoip>, ["~> 1.2.1"])
      s.add_development_dependency(%q<time_diff>, ["~> 0.3.0"])
    else
      s.add_dependency(%q<geoip>, ["~> 1.2.1"])
      s.add_dependency(%q<time_diff>, ["~> 0.3.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<geoip>, ["~> 1.2.1"])
      s.add_dependency(%q<time_diff>, ["~> 0.3.0"])
    end
  else
    s.add_dependency(%q<geoip>, ["~> 1.2.1"])
    s.add_dependency(%q<time_diff>, ["~> 0.3.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<geoip>, ["~> 1.2.1"])
    s.add_dependency(%q<time_diff>, ["~> 0.3.0"])
  end
end

